### ISSUE TITLE
Nome do Usuário/E-mail não aparecem no Menu

### ISSUE THREAD

**Issue by wowbaggerBR** [wowbaggerBR/Salarium#15]
Precisa implementar a leitura dos atributos do usuário a partir do FirebaseAuth para alimentar essas caixas de texto. Correção simples, deve ser integrada com a implementação final (oremos) do RecyclerView.

**Comment by wowbaggerBR** [comment]
@WilliamSenoski coloquei você de responsável por essa porque você tá tocando praticamente tudo relacionado à MainActivity, Resumo e seus Fragments.

**Comment by WilliamSenoski** [comment]
Foi efetuado a verificação do e-mail do usuário logado, mas aparentemente existe um bug que ocorre com o método getDisplayName() que retornaria o nome do usuário logado mas está vindo nulo. Irei investigar mais a respeito e se já foi corrigido na versão que utilizamos atualmente.

**Comment by wowbaggerBR** [comment]
A sugestão que eu penso seria pegar o nome do banco, diretamente por referência e childs, e não pelo Auth. Dá pra pegar os dados por idUsuario como um objeto Usuario, ou então pegar só o nome dentro do Snapshot e mandar pro textView.
