### ISSUE TITLE
DatePicker em Recebi/Gastei bloqueando escolha de datas passadas

### ISSUE THREAD

**Issue by wowbaggerBR** [wowbaggerBR/Salarium#37]
A inclusão de entradas de datas passadas gera childs fora de ordem no Firebase e isso acaba gerando uma série de problemas nas telas de Relatórios e Gráficos.

Uma forma temporária de corrigir isso seria impedir que os datePickers permitam escolha de datas passadas. A mesma solução já foi aplicada em Contas à Vencer, basta copiar.

**Comment by WilliamSenoski** [comment]
Arrumado! futuramente podemos ver como corrigir esse problema de outra forma
